# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('play_object', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='play.Play')),
            ],
        ),
    ]
