# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20170708_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
